<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Sarfaraj_Doni" name="ExtentWithParallelClasses" tests="2" failures="1" timestamp="15 Mar 2016 13:13:06 GMT" time="1.034" errors="0">
  <testcase name="Test1" time="0.013" classname="home.Link.TestCase1"/>
  <testcase name="Test2" time="0.014" classname="home.Link.TestCase2">
    <failure type="java.lang.AssertionError" message="expected [fail] but found [pass]">
      <![CDATA[java.lang.AssertionError: expected [fail] but found [pass]
	at home.Link.TestCase2.Test2(TestCase2.java:28)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
</testsuite> <!-- ExtentWithParallelClasses -->
